# This is the config file for the SAM2 Video labeling tool

# Select the mode, the default mode is list mode. ONLY SET ONE MODE TO TRUE
mode:
  list_mode : True  # Follows a Table and opens the next entry in the table, when you close the window
  test_mode : False # Opens the locally saved test_mode folder as its input
  view_mode : False # View Mode enables a button, to select a folder with the json and the original frames folder in it, and displays them, with their labeling
  auto_mode : False # Use a pretrained yolo model for labeling. NOT IMPLEMENTED YET!


sam_model_paths:
  # Put in here the path to your SAM2 Checkpoint:
  sam2_checkpoint : C:\Users\K3000\sam2\checkpoints\sam2.1_hiera_tiny.pt

  # This is the config path for your selected model. The path itself is the same for all models, just change the last letter accordingly:
  # tiny = t
  # small = s
  # base plus = b+
  # large = l
  model_cfg : configs/sam2.1/sam2.1_hiera_t.yaml


default_paths:
  output_path : C:\Code Python\SAM2-Interactive-Object-Labeling-Project\labeling_project
  table_path: C:\Code Python\SAM2-Interactive-Object-Labeling-Project\Infos and Tables\Max Info\max_liste.csv


# Put in here the columns, which then can be saved in your result jsons
default_table_columns:
  - Inspektions-ID
  - Videoname
  - Rohrmaterial
  - Inspekteur-Name
  - Extracted Frame Rate
  - Rohrprofil
  - Rohrhöhe (mm)
  - Rohrbreite (mm)
  - Videohash
  - Schadenskürzel
  - Videozeitpunkt (h:min:sec)



#### Here are all the presets for the test mode ####
test_mode_setup:
  current_frame_dir : C:\Code Python\automation-with-sam2\labeling_project\test folder\source images
  video_path : C:\Code Python\automation-with-sam2\labeling_project\test folder\test.mp4


test_mode_table:
  Inspektions-ID : 1
  Videoname: test.mp4
  Rohrmaterial: Stein
  Inspekteur-Name: Batagan
  Extracted Frame Rate: 25
  Rohrprofil: Rund
  Rohrhöhe (mm): 1
  Rohrbreite (mm): 1
  Videohash: 12345
  Schadenskürzel: Root
  Videozeitpunkt (h:min:sec): 00:00:20